In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

import spacy

In [2]:
df = pd.read_csv("../data/raw_hr_data.csv")
pd.set_option("display.max_colwidth", None)
df.head()

,id,job_title,location,connection,fit
0,1,2019 C.T. Bauer College of Business Graduate (Magna Cum Laude) and aspiring Human Resources professional,"Houston, Texas",85,NaN
1,2,Native English Teacher at EPIK (English Program in Korea),Kanada,500+,NaN
2,3,Aspiring Human Resources Professional,"Raleigh-Durham, North Carolina Area",44,NaN
3,4,People Development Coordinator at Ryan,"Denton, Texas",500+,NaN
4,5,Advisory Board Member at Celal Bayar University,"İzmir, Türkiye",500+,NaN

In [3]:
df = df.drop("fit",axis=1)
df['connection'] = df['connection'].replace("500+ ","500")
df = df.drop_duplicates(subset=['job_title'])
# looking for non english alphabets using regex 
df[df["location"].str.contains(r"[^\x00-\x7F]", regex=True, na=False)]

,id,job_title,location,connection
4,5,Advisory Board Member at Celal Bayar University,"İzmir, Türkiye",500
77,78,Human Resources Generalist at Schwan's,Amerika Birleşik Devletleri,500
93,94,Seeking Human Resources Opportunities. Open to travel and relocation.,Amerika Birleşik Devletleri,415

In [4]:
df['location'] = df['location'].str.replace("ü","u")
df['location'] = df['location'].str.replace("ş","s")
df['location'] = df['location'].str.replace("İ","I")

In [5]:
df["all_data"] = (
    df["job_title"].astype(str) + " " +
    df["location"].astype(str)
)

In [6]:
labels_hr_resources = [1,0,1,0,0,1,1,1,1,0,0,
                       1,1,1,1,1,1,1,1,1,1,1,
                       1,1,1,1,1,1,0,1,1,1,1,
                       0,0,0,1,1,0,0,0,0,1,0,
                       0,0,1,1,1,0,0,0]

df['relevance'] = labels_hr_resources

In [7]:
df.head(60)

,id,job_title,location,connection,all_data,relevance
0,1,2019 C.T. Bauer College of Business Graduate (Magna Cum Laude) and aspiring Human Resources professional,"Houston, Texas",85,"2019 C.T. Bauer College of Business Graduate (Magna Cum Laude) and aspiring Human Resources professional Houston, Texas",1
1,2,Native English Teacher at EPIK (English Program in Korea),Kanada,500,Native English Teacher at EPIK (English Program in Korea) Kanada,0
2,3,Aspiring Human Resources Professional,"Raleigh-Durham, North Carolina Area",44,"Aspiring Human Resources Professional Raleigh-Durham, North Carolina Area",1
3,4,People Development Coordinator at Ryan,"Denton, Texas",500,"People Development Coordinator at Ryan Denton, Texas",0
4,5,Advisory Board Member at Celal Bayar University,"Izmir, Turkiye",500,"Advisory Board Member at Celal Bayar University Izmir, Turkiye",0
5,6,Aspiring Human Resources Specialist,Greater New York City Area,1,Aspiring Human Resources Specialist Greater New York City Area,1
6,7,Student at Humber College and Aspiring Human Resources Generalist,Kanada,61,Student at Humber College and Aspiring Human Resources Generalist Kanada,1
7,8,HR Senior Specialist,San Francisco Bay Area,500,HR Senior Specialist San Francisco Bay Area,1
9,10,Seeking Human Resources HRIS and Generalist Positions,Greater Philadelphia Area,500,Seeking Human Resources HRIS and Generalist Positions Greater Philadelphia Area,1
10,11,Student at Chapman University,"Lake Forest, California",2,"Student at Chapman University Lake Forest, California",0
11,12,"SVP, CHRO, Marketing & Communications, CSR Officer | ENGIE | Houston | The Woodlands | Energy | GPHR | SPHR","Houston, Texas Area",500,"SVP, CHRO, Marketing & Communications, CSR Officer | ENGIE | Houston | The Woodlands | Energy | GPHR | SPHR Houston, Texas Area",0
12,13,Human Resources Coordinator at InterContinental Buckhead Atlanta,"Atlanta, Georgia",500,"Human Resources Coordinator at InterContinental Buckhead Atlanta Atlanta, Georgia",1
26,27,Aspiring Human Resources Management student seeking an internship,"Houston, Texas Area",500,"Aspiring Human Resources Management student seeking an internship Houston, Texas Area",1
27,28,Seeking Human Resources Opportunities,"Chicago, Illinois",390,"Seeking Human Resources Opportunities Chicago, Illinois",1
65,66,Experienced Retail Manager and aspiring Human Resources Professional,"Austin, Texas Area",57,"Experienced Retail Manager and aspiring Human Resources Professional Austin, Texas Area",1
66,67,"Human Resources, Staffing and Recruiting Professional","Jackson, Mississippi Area",500,"Human Resources, Staffing and Recruiting Professional Jackson, Mississippi Area",1
67,68,Human Resources Specialist at Luxottica,Greater New York City Area,500,Human Resources Specialist at Luxottica Greater New York City Area,1
68,69,"Director of Human Resources North America, Groupe Beneteau","Greater Grand Rapids, Michigan Area",500,"Director of Human Resources North America, Groupe Beneteau Greater Grand Rapids, Michigan Area",1
69,70,"Retired Army National Guard Recruiter, office manager, seeking a position in Human Resources.","Virginia Beach, Virginia",82,"Retired Army National Guard Recruiter, office manager, seeking a position in Human Resources. Virginia Beach, Virginia",1
70,71,"Human Resources Generalist at ScottMadden, Inc.","Raleigh-Durham, North Carolina Area",500,"Human Resources Generalist at ScottMadden, Inc. Raleigh-Durham, North Carolina Area",1
71,72,Business Management Major and Aspiring Human Resources Manager,"Monroe, Louisiana Area",5,"Business Management Major and Aspiring Human Resources Manager Monroe, Louisiana Area",1
72,73,"Aspiring Human Resources Manager, seeking internship in Human Resources.","Houston, Texas Area",7,"Aspiring Human Resources Manager, seeking internship in Human Resources. Houston, Texas Area",1
73,74,Human Resources Professional,Greater Boston Area,16,Human Resources Professional Greater Boston Area,1
74,75,"Nortia Staffing is seeking Human Resources, Payroll & Administrative Professionals!! (408) 709-2621","San Jose, California",500,"Nortia Staffing is seeking Human Resources, Payroll & Administrative Professionals!! (408) 709-2621 San Jose, California",1
75,76,Aspiring Human Resources Professional | Passionate about helping to create an inclusive and engaging work environment,"New York, New York",212,"Aspiring Human Resources Professional | Passionate about helping to create an inclusive and engaging work environment New York, New York",1
76,77,Human Resources|\nConflict Management|\nPolicies & Procedures|Talent Management|Benefits & Compensation,Dallas/Fort Worth Area,409,Human Resources|\nConflict Management|\nPolicies & Procedures|Talent Management|Benefits & Compensation Dallas/Fort Worth Area,1
77,78,Human Resources Generalist at Schwan's,Amerika Birlesik Devletleri,500,Human Resources Generalist at Schwan's Amerika Birlesik Devletleri,1
78,79,Liberal Arts Major. Aspiring Human Resources Analyst.,"Baton Rouge, Louisiana Area",7,"Liberal Arts Major. Aspiring Human Resources Analyst. Baton Rouge, Louisiana Area",1
79,80,Junior MES Engineer| Information Systems,"Myrtle Beach, South Carolina Area",52,"Junior MES Engineer| Information Systems Myrtle Beach, South Carolina Area",0
80,81,Senior Human Resources Business Partner at Heil Environmental,"Chattanooga, Tennessee Area",455,"Senior Human Resources Business Partner at Heil Environmental Chattanooga, Tennessee Area",1
81,82,Aspiring Human Resources Professional | An energetic and Team-Focused Leader,"Austin, Texas Area",174,"Aspiring Human Resources Professional | An energetic and Team-Focused Leader Austin, Texas Area",1
82,83,HR Manager at Endemol Shine North America,"Los Angeles, California",268,"HR Manager at Endemol Shine North America Los Angeles, California",1
83,84,Human Resources professional for the world leader in GIS software,"Highland, California",50,"Human Resources professional for the world leader in GIS software Highland, California",1
84,85,RRP Brand Portfolio Executive at JTI (Japan Tobacco International),Greater Philadelphia Area,500,RRP Brand Portfolio Executive at JTI (Japan Tobacco International) Greater Philadelphia Area,0
85,86,Information Systems Specialist and Programmer with a love for data and organization.,"Gaithersburg, Maryland",4,"Information Systems Specialist and Programmer with a love for data and organization. Gaithersburg, Maryland",0
86,87,Bachelor of Science in Biology from Victoria University of Wellington,"Baltimore, Maryland",40,"Bachelor of Science in Biology from Victoria University of Wellington Baltimore, Maryland",0
87,88,Human Resources Management Major,"Milpitas, California",18,"Human Resources Management Major Milpitas, California",1
88,89,Director Human Resources at EY,Greater Atlanta Area,349,Director Human Resources at EY Greater Atlanta Area,1
89,90,Undergraduate Research Assistant at Styczynski Lab,Greater Atlanta Area,155,Undergraduate Research Assistant at Styczynski Lab Greater Atlanta Area,0
90,91,Lead Official at Western Illinois University,Greater Chicago Area,39,Lead Official at Western Illinois University Greater Chicago Area,0
91,92,Seeking employment opportunities within Customer Service or Patient Care,"Torrance, California",64,"Seeking employment opportunities within Customer Service or Patient Care Torrance, California",0
92,93,Admissions Representative at Community medical center long beach,"Long Beach, California",9,"Admissions Representative at Community medical center long beach Long Beach, California",0
93,94,Seeking Human Resources Opportunities. Open to travel and relocation.,Amerika Birlesik Devletleri,415,Seeking Human Resources Opportunities. Open to travel and relocation. Amerika Birlesik Devletleri,1
94,95,Student at Westfield State University,"Bridgewater, Massachusetts",57,"Student at Westfield State University Bridgewater, Massachusetts",0
95,96,Student at Indiana University Kokomo - Business Management - \nRetail Manager at Delphi Hardware and Paint,"Lafayette, Indiana",19,"Student at Indiana University Kokomo - Business Management - \nRetail Manager at Delphi Hardware and Paint Lafayette, Indiana",0
97,98,Student,"Houston, Texas Area",4,"Student Houston, Texas Area",0
98,99,Seeking Human Resources Position,"Las Vegas, Nevada Area",48,"Seeking Human Resources Position Las Vegas, Nevada Area",1
99,100,Aspiring Human Resources Manager | Graduating May 2020 | Seeking an Entry-Level Human Resources Position in St. Louis,"Cape Girardeau, Missouri",103,"Aspiring Human Resources Manager | Graduating May 2020 | Seeking an Entry-Level Human Resources Position in St. Louis Cape Girardeau, Missouri",1
100,101,Human Resources Generalist at Loparex,"Raleigh-Durham, North Carolina Area",500,"Human Resources Generalist at Loparex Raleigh-Durham, North Carolina Area",1
101,102,Business Intelligence and Analytics at Travelers,Greater New York City Area,49,Business Intelligence and Analytics at Travelers Greater New York City Area,0
102,103,Always set them up for Success,Greater Los Angeles Area,500,Always set them up for Success Greater Los Angeles Area,0
103,104,Director Of Administration at Excellence Logging,"Katy, Texas",500,"Director Of Administration at Excellence Logging Katy, Texas",0

In [8]:
#!python -m spacy download en_core_web_sm
nlp = spacy.load("en_core_web_sm")

The idea is to build a function and apply it to each row in the job title column. The function tokenizes the text, removes punctuation and stop words, converts the words to lowercase, lemmatizes them, and returns the cleaned words as a list for each row in the job_title and return the join str becasue each model will use its own tokenization method.

In [9]:
def clean_title(text):
    doc = nlp(text)

    clean_text = []

    for token in doc:
        if not token.is_stop and not token.is_punct:
            clean_text.append(token.lemma_.lower())

    return " ".join(clean_text)

In [10]:
df["clean_job_title"] = df["all_data"].apply(clean_title)

In [11]:
df = df.drop("all_data",axis=1)

In [12]:
df.to_csv("../data/clean_hr_data.csv", index=False)

In [16]:
df.columns

Index(['id', 'job_title', 'location', 'connection', 'relevance',
       'clean_job_title'],
      dtype='object')

In [13]:
df_rag = df.drop(['job_title', 'location', 'connection', 'relevance'], axis=1)

In [14]:
df_rag.to_csv("../data/rag_hr_data.csv", index=False)