In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

import spacy
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer
import gensim.downloader as api
from sklearn.metrics.pairwise import cosine_similarity
import torch
from transformers import AutoTokenizer, AutoModel
from transformers import pipeline

In [2]:
df = pd.read_csv("../data/clean_hr_data.csv")

In [3]:
measure_rank_1 = "aspiring human resources" 
measure_rank_2 =  "seeking human resources"

In [4]:
# BOW method 
# You fit and transform on the column
# you only transform the y1 and y2
vectorizer_bow = CountVectorizer()
X = vectorizer_bow.fit_transform(df['clean_job_title'])
y1 = vectorizer_bow.transform([measure_rank_1])
y2 = vectorizer_bow.transform([measure_rank_2])

score_1 = cosine_similarity(y1, X)
score_2 = cosine_similarity(y2, X)

df["similarity_1_bow"] = score_1.flatten()
df[df["similarity_1_bow"]>0.3][["clean_job_title", "similarity_1_bow"]].sort_values(
    by="similarity_1_bow",
    ascending=False
).head(10)

                                      clean_job_title  similarity_1_bow
21  aspiring human resources manager seek internsh...          0.745356
47  aspiring human resources manager | graduating ...          0.629941
6   student humber college aspiring human resource...          0.612372
5   aspiring human resources specialist greater ne...          0.577350
2   aspiring human resources professional raleigh ...          0.577350
12  aspiring human resources management student se...          0.547723
20  business management major aspiring human resou...          0.547723
30  aspiring human resources professional | energe...          0.522233
22   human resources professional greater boston area          0.471405
36  human resources management major milpitas cali...          0.471405

In [5]:
df["similarity_2_bow"] = score_2.flatten()
df[df["similarity_2_bow"]>0.3][["clean_job_title", "similarity_2_bow"]].sort_values(
    by="similarity_2_bow",
    ascending=False
).head(10)

                                      clean_job_title  similarity_2_bow
21  aspiring human resources manager seek internsh...          0.730297
47  aspiring human resources manager | graduating ...          0.617213
13  seek human resources opportunities chicago ill...          0.577350
22   human resources professional greater boston area          0.577350
36  human resources management major milpitas cali...          0.577350
37  director human resources   ey greater atlanta ...          0.534522
26  human resources generalist schwan amerika birl...          0.534522
15  human resources staffing recruiting profession...          0.500000
46  seek human resources position las vegas nevada...          0.500000
6   student humber college aspiring human resource...          0.500000

In [6]:
# Tfidf method
vectorizer_tfidf = TfidfVectorizer()
X = vectorizer_tfidf.fit_transform(df['clean_job_title'])
y1 = vectorizer_tfidf.transform([measure_rank_1])
y2 = vectorizer_tfidf.transform([measure_rank_2])

score_1 = cosine_similarity(y1, X)
score_2 = cosine_similarity(y2, X)


df["similarity_1_tfidf"] = score_1.flatten()
df[df["similarity_1_tfidf"]>0.3][["clean_job_title", "similarity_1_tfidf"]].sort_values(
    by="similarity_1_tfidf",
    ascending=False
).head(10)

                                      clean_job_title  similarity_1_tfidf
21  aspiring human resources manager seek internsh...            0.547299
5   aspiring human resources specialist greater ne...            0.416505
2   aspiring human resources professional raleigh ...            0.410821
12  aspiring human resources management student se...            0.401339
6   student humber college aspiring human resource...            0.383511
20  business management major aspiring human resou...            0.361899
47  aspiring human resources manager | graduating ...            0.321200
30  aspiring human resources professional | energe...            0.319760

In [7]:
df["similarity_2_tfidf"] = score_2.flatten()
df[df["similarity_2_tfidf"]>0.3][["clean_job_title", "similarity_2_tfidf"]].sort_values(
    by="similarity_2_tfidf",
    ascending=False
).head(10)

                                      clean_job_title  similarity_2_tfidf
21  aspiring human resources manager seek internsh...            0.491453
22   human resources professional greater boston area            0.339593

In [8]:
#%pip install gensim

model = api.load('glove-wiki-gigaword-100')


# apply has the tendency to work on the rows automatically 
def get_title_vector(row):
    words = row.split()

    vectors = []

    for word in words:
        if word in model:
            vectors.append(model[word])

    return np.mean(vectors, axis=0)


    
df['vector_for_modeling'] = df["clean_job_title"].apply(get_title_vector)
y1_vector = get_title_vector(measure_rank_1)
y2_vector = get_title_vector(measure_rank_2)


X_glove = np.vstack(df["vector_for_modeling"])
# to make it work you need to use vstack function
score_1 = cosine_similarity(
    y1_vector.reshape(1, -1),
    X_glove
)

score_2 = cosine_similarity(
    y2_vector.reshape(1, -1),
    X_glove
)

df["similarity_1_glove"] = score_1.flatten()
# turns a multi-dimensional NumPy array into a one-dimensional array
df[df["similarity_1_glove"]>0.3][["clean_job_title", "similarity_1_glove"]].sort_values(
    by="similarity_1_glove",
    ascending=False
).head(10)

                                      clean_job_title  similarity_1_glove
21  aspiring human resources manager seek internsh...            0.873273
22   human resources professional greater boston area            0.832801
13  seek human resources opportunities chicago ill...            0.829122
24  aspiring human resources professional | passio...            0.829009
37  director human resources   ey greater atlanta ...            0.817207
5   aspiring human resources specialist greater ne...            0.816461
8   seek human resources hris generalist positions...            0.815399
12  aspiring human resources management student se...            0.814947
32  human resources professional world leader gis ...            0.814346
36  human resources management major milpitas cali...            0.794404

In [9]:
df["similarity_2_glove"] = score_2.flatten()
# turns a multi-dimensional NumPy array into a one-dimensional array
df[df["similarity_2_glove"]>0.3][["clean_job_title", "similarity_2_glove"]].sort_values(
    by="similarity_2_glove",
    ascending=False
).head(10)

                                      clean_job_title  similarity_2_glove
21  aspiring human resources manager seek internsh...            0.887125
13  seek human resources opportunities chicago ill...            0.886082
8   seek human resources hris generalist positions...            0.875451
42  seek human   resources opportunity open travel...            0.872547
22   human resources professional greater boston area            0.848357
37  director human resources   ey greater atlanta ...            0.840632
36  human resources management major milpitas cali...            0.840518
12  aspiring human resources management student se...            0.814407
24  aspiring human resources professional | passio...            0.809889
16  human resources specialist luxottica greater n...            0.809206

In [10]:
tokenizer = AutoTokenizer.from_pretrained("bert-base-uncased")
bert = AutoModel.from_pretrained("bert-base-uncased")

def get_title_vector_bert(text):

    inputs = tokenizer(
        text,
        return_tensors="pt",
        truncation=True,
        padding=True
    )
# pt is py_torch, truncation for fitting what the model allow in size, padding makes the size the same
    with torch.no_grad():
        outputs = bert(**inputs)


    vector = outputs.last_hidden_state.mean(dim=1)

    return vector.squeeze().numpy()
# make the tensor a numpy array with one dimension 
df['bert_for_modeling'] = df["clean_job_title"].apply(get_title_vector_bert)
y1_vector = get_title_vector(measure_rank_1)
y2_vector = get_title_vector(measure_rank_2)



X_bert = np.vstack(df["bert_for_modeling"])

y1_vector = get_title_vector_bert(measure_rank_1)
y2_vector = get_title_vector_bert(measure_rank_2)

score_1 = cosine_similarity(
    y1_vector.reshape(1, -1),
    X_bert
)

score_2 = cosine_similarity(
    y2_vector.reshape(1, -1),
    X_bert
)

df["similarity_1_bert"] = score_1.flatten()

df[df["similarity_1_bert"]>0.3][["clean_job_title", "similarity_1_bert"]].sort_values(
    by="similarity_1_bert",
    ascending=False
).head(10)

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

[transformers] BertModel LOAD REPORT from: bert-base-uncased
Key                                        | Status     |  |
-------------------------------------------+------------+--+-
cls.predictions.bias                       | UNEXPECTED |  |
cls.predictions.transform.dense.weight     | UNEXPECTED |  |
cls.seq_relationship.bias                  | UNEXPECTED |  |
cls.seq_relationship.weight                | UNEXPECTED |  |
cls.predictions.transform.dense.bias       | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.

                                      clean_job_title  similarity_1_bert
13  seek human resources opportunities chicago ill...           0.756244
21  aspiring human resources manager seek internsh...           0.751372
30  aspiring human resources professional | energe...           0.738730
6   student humber college aspiring human resource...           0.734590
14  experienced retail manager aspire human resour...           0.731170
20  business management major aspiring human resou...           0.716073
12  aspiring human resources management student se...           0.715341
15  human resources staffing recruiting profession...           0.711508
51  director administration excellence logging kat...           0.710626
32  human resources professional world leader gis ...           0.706642

In [11]:
df["similarity_2_bert"] = score_2.flatten()

df[df["similarity_2_bert"]>0.3][["clean_job_title", "similarity_2_bert"]].sort_values(
    by="similarity_2_bert",
    ascending=False
).head(10)

                                      clean_job_title  similarity_2_bert
13  seek human resources opportunities chicago ill...           0.822273
15  human resources staffing recruiting profession...           0.704242
21  aspiring human resources manager seek internsh...           0.698324
51  director administration excellence logging kat...           0.695820
8   seek human resources hris generalist positions...           0.693475
40  seek employment opportunity customer service p...           0.693326
3    people development coordinator ryan denton texas           0.686898
37  director human resources   ey greater atlanta ...           0.682326
22   human resources professional greater boston area           0.681378
14  experienced retail manager aspire human resour...           0.670993

In [12]:
tokenizer = AutoTokenizer.from_pretrained(
    "sentence-transformers/all-MiniLM-L6-v2"
)

sbert = AutoModel.from_pretrained(
    "sentence-transformers/all-MiniLM-L6-v2"
)


def get_title_vector_sbert(text):

    inputs = tokenizer(
        text,
        return_tensors="pt",
        truncation=True,
        padding=True
    )

    with torch.no_grad():
        outputs = sbert(**inputs)

    # Token embeddings
    token_embeddings = outputs.last_hidden_state

    # Attention mask
    attention_mask = inputs["attention_mask"]

    # Expand mask to same dimensions as embeddings
    mask = attention_mask.unsqueeze(-1).expand(token_embeddings.size()).float()

    # Mean pooling, ignoring padding tokens
    vector = (token_embeddings * mask).sum(dim=1) / mask.sum(dim=1)

    return vector.squeeze().numpy()


df["sbert_for_modeling"] = df["clean_job_title"].apply(
    get_title_vector_sbert
)


s_bert = np.vstack(df["sbert_for_modeling"])

y1_vector = get_title_vector_sbert(measure_rank_1)
y2_vector = get_title_vector_sbert(measure_rank_2)

score_1 = cosine_similarity(
    y1_vector.reshape(1, -1),
    s_bert
)

score_2 = cosine_similarity(
    y2_vector.reshape(1, -1),
    s_bert
)

df["similarity_1_sbert"] = score_1.flatten()

df[df["similarity_1_sbert"]>0.3][["clean_job_title", "similarity_1_sbert"]].sort_values(
    by="similarity_1_sbert",
    ascending=False
).head(10)

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

                                      clean_job_title  similarity_1_sbert
2   aspiring human resources professional raleigh ...            0.842901
5   aspiring human resources specialist greater ne...            0.787457
47  aspiring human resources manager | graduating ...            0.776213
30  aspiring human resources professional | energe...            0.726663
21  aspiring human resources manager seek internsh...            0.717666
12  aspiring human resources management student se...            0.710845
46  seek human resources position las vegas nevada...            0.708507
24  aspiring human resources professional | passio...            0.689745
13  seek human resources opportunities chicago ill...            0.678825
6   student humber college aspiring human resource...            0.675802

In [13]:
df["similarity_2_sbert"] = score_2.flatten()

df[df["similarity_2_sbert"]>0.3][["clean_job_title", "similarity_2_sbert"]].sort_values(
    by="similarity_2_sbert",
    ascending=False
).head(10)

                                      clean_job_title  similarity_2_sbert
46  seek human resources position las vegas nevada...            0.765440
2   aspiring human resources professional raleigh ...            0.749284
5   aspiring human resources specialist greater ne...            0.713229
13  seek human resources opportunities chicago ill...            0.712608
48  human resources generalist loparex raleigh dur...            0.712407
8   seek human resources hris generalist positions...            0.712170
22   human resources professional greater boston area            0.660824
21  aspiring human resources manager seek internsh...            0.656847
47  aspiring human resources manager | graduating ...            0.656618
30  aspiring human resources professional | energe...            0.650934

In [14]:
tokenizer = AutoTokenizer.from_pretrained(
    "intfloat/e5-small-v2"
)

e5 = AutoModel.from_pretrained(
    "intfloat/e5-small-v2"
)


def get_title_vector_e5(text):

    inputs = tokenizer(
        text,
        return_tensors="pt",
        truncation=True,
        padding=True
    )

    with torch.no_grad():
        outputs = e5(**inputs)

    # Token embeddings
    token_embeddings = outputs.last_hidden_state

    # Attention mask
    attention_mask = inputs["attention_mask"]

    # Expand mask to same dimensions as embeddings
    mask = attention_mask.unsqueeze(-1).expand(
        token_embeddings.size()
    ).float()

    # Mean pooling
    vector = (token_embeddings * mask).sum(dim=1) / mask.sum(dim=1)

    return vector.squeeze().numpy()


df["e5_for_modeling"] = df["clean_job_title"].apply(
    get_title_vector_e5
)




X_e5 = np.vstack(df["e5_for_modeling"])

y1_vector = get_title_vector_e5(measure_rank_1)
y2_vector = get_title_vector_e5(measure_rank_2)


score_1 = cosine_similarity(
    y1_vector.reshape(1, -1),
    X_e5
)

df["similarity_1_5e"] = score_1.flatten()

df[df["similarity_1_5e"]>0.3][["clean_job_title", "similarity_1_5e"]].sort_values(
    by="similarity_1_5e",
    ascending=False
).head(10)

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

                                      clean_job_title  similarity_1_5e
5   aspiring human resources specialist greater ne...         0.901982
21  aspiring human resources manager seek internsh...         0.897031
2   aspiring human resources professional raleigh ...         0.894147
47  aspiring human resources manager | graduating ...         0.894092
24  aspiring human resources professional | passio...         0.884487
12  aspiring human resources management student se...         0.882906
30  aspiring human resources professional | energe...         0.879660
13  seek human resources opportunities chicago ill...         0.874558
15  human resources staffing recruiting profession...         0.864990
20  business management major aspiring human resou...         0.862209

In [15]:
score_2 = cosine_similarity(
    y2_vector.reshape(1, -1),
    X_e5
)

df["similarity_2_5e"] = score_2.flatten()

df[df["similarity_2_5e"]>0.3][["clean_job_title", "similarity_2_5e"]].sort_values(
    by="similarity_2_5e",
    ascending=False
).head(10)

                                      clean_job_title  similarity_2_5e
13  seek human resources opportunities chicago ill...         0.907182
46  seek human resources position las vegas nevada...         0.894789
21  aspiring human resources manager seek internsh...         0.885686
8   seek human resources hris generalist positions...         0.879234
42  seek human   resources opportunity open travel...         0.875551
47  aspiring human resources manager | graduating ...         0.873214
12  aspiring human resources management student se...         0.870509
5   aspiring human resources specialist greater ne...         0.866386
24  aspiring human resources professional | passio...         0.862875
2   aspiring human resources professional raleigh ...         0.858127

In [16]:
tokenizer = AutoTokenizer.from_pretrained(
    "BAAI/bge-small-en-v1.5"
)

bge = AutoModel.from_pretrained(
    "BAAI/bge-small-en-v1.5"
)


def get_title_vector_bge(text):

    inputs = tokenizer(
        text,
        return_tensors="pt",
        truncation=True,
        padding=True
    )

    with torch.no_grad():
        outputs = bge(**inputs)

    # Token embeddings
    token_embeddings = outputs.last_hidden_state

    # Attention mask
    attention_mask = inputs["attention_mask"]

    # Expand mask to same dimensions as embeddings
    mask = attention_mask.unsqueeze(-1).expand(
        token_embeddings.size()
    ).float()

    # Mean pooling
    vector = (token_embeddings * mask).sum(dim=1) / mask.sum(dim=1)

    return vector.squeeze().numpy() 


df["bge_for_modeling"] = df["clean_job_title"].apply(
    get_title_vector_bge
)


X_bge = np.vstack(df["bge_for_modeling"])

y1_vector = get_title_vector_bge(measure_rank_1)
y2_vector = get_title_vector_bge(measure_rank_2)

score_1 = cosine_similarity(
    y1_vector.reshape(1, -1),
    X_bge
)

df["similarity_1_bge"] = score_1.flatten()
# Chain the filtering and sorting together
df[df["similarity_1_bge"] > 0.3][["clean_job_title", "similarity_1_bge"]].sort_values(
    by="similarity_1_bge",
    ascending=False
).head(10)

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

                                      clean_job_title  similarity_1_bge
2   aspiring human resources professional raleigh ...          0.815475
5   aspiring human resources specialist greater ne...          0.800074
21  aspiring human resources manager seek internsh...          0.787040
24  aspiring human resources professional | passio...          0.784607
30  aspiring human resources professional | energe...          0.764258
12  aspiring human resources management student se...          0.763715
47  aspiring human resources manager | graduating ...          0.763419
20  business management major aspiring human resou...          0.756249
13  seek human resources opportunities chicago ill...          0.754647
6   student humber college aspiring human resource...          0.721071

In [17]:
score_2 = cosine_similarity(
    y2_vector.reshape(1, -1),
    X_bge
)

df["similarity_2_bge"] = score_2.flatten()

df[df["similarity_2_bge"] > 0.3][["clean_job_title", "similarity_2_bge"]].sort_values(
    by="similarity_2_bge",
    ascending=False
).head(10)

                                      clean_job_title  similarity_2_bge
13  seek human resources opportunities chicago ill...          0.839602
46  seek human resources position las vegas nevada...          0.789876
8   seek human resources hris generalist positions...          0.774203
2   aspiring human resources professional raleigh ...          0.770838
21  aspiring human resources manager seek internsh...          0.766566
5   aspiring human resources specialist greater ne...          0.751435
15  human resources staffing recruiting profession...          0.751198
42  seek human   resources opportunity open travel...          0.742584
22   human resources professional greater boston area          0.738667
24  aspiring human resources professional | passio...          0.725922

In [18]:
df

,id,job_title,location,connection,relevance,clean_job_title,similarity_1_bow,similarity_2_bow,similarity_1_tfidf,similarity_2_tfidf,...,similarity_2_bert,sbert_for_modeling,similarity_1_sbert,similarity_2_sbert,e5_for_modeling,similarity_1_5e,similarity_2_5e,bge_for_modeling,similarity_1_bge,similarity_2_bge
0,1,2019 C.T. Bauer College of Business Graduate (...,"Houston, Texas",85,1,2019 c.t. bauer college business graduate magn...,0.308607,0.377964,0.099687,0.159870,...,0.551268,"[-0.34165978, 0.071470454, 0.012781473, -0.018...",0.390027,0.282561,"[-0.5084922, 0.34237465, 0.5676787, 0.05718790...",0.820726,0.793657,"[-0.40054908, 0.3582064, 0.023666572, -0.32824...",0.610130,0.579220
1,2,Native English Teacher at EPIK (English Progra...,Kanada,500,0,native english teacher epik english program ko...,0.000000,0.000000,0.000000,0.000000,...,0.575211,"[-0.007482983, 0.04508299, 0.2542144, -0.04180...",0.148046,0.141916,"[-0.456203, 0.33561006, 0.21070337, -0.0901796...",0.763373,0.745414,"[-0.16465878, 0.20876308, 0.69340354, -0.24499...",0.477236,0.465852
2,3,Aspiring Human Resources Professional,"Raleigh-Durham, North Carolina Area",44,1,aspiring human resources professional raleigh ...,0.577350,0.471405,0.410821,0.256167,...,0.632049,"[0.03896105, 0.07679981, -0.268583, 0.6749405,...",0.842901,0.749284,"[-0.65419954, 0.20865859, 0.11589524, 0.170229...",0.894147,0.858127,"[-0.27730662, 0.7022705, 0.0535323, -0.2380222...",0.815475,0.770838
3,4,People Development Coordinator at Ryan,"Denton, Texas",500,0,people development coordinator ryan denton texas,0.000000,0.000000,0.000000,0.000000,...,0.686898,"[-0.39900938, -0.07422431, -0.068586335, 0.074...",0.391778,0.384026,"[-0.80403244, 0.4648779, 0.4698457, -0.1501685...",0.806019,0.797369,"[-0.10203578, -0.112945706, 0.14424647, -0.425...",0.582874,0.615213
4,5,Advisory Board Member at Celal Bayar University,"Izmir, Turkiye",500,0,advisory board member celal bayar university i...,0.000000,0.000000,0.000000,0.000000,...,0.329493,"[-0.29537693, 0.201363, -0.009500056, -0.00230...",0.243675,0.222491,"[-0.44008344, 0.26205158, 0.22837786, -0.06000...",0.743727,0.745177,"[0.0032356717, 0.41211772, 0.40210912, -0.4016...",0.453267,0.442491
5,6,Aspiring Human Resources Specialist,Greater New York City Area,1,1,aspiring human resources specialist greater ne...,0.577350,0.471405,0.416505,0.259712,...,0.639155,"[0.09876519, -0.10893437, 0.022738159, 0.52238...",0.787457,0.713229,"[-0.61147654, 0.3599533, 0.3801304, 0.16546346...",0.901982,0.866386,"[0.2279015, 0.38759235, 0.5125312, -0.3389072,...",0.800074,0.751435
6,7,Student at Humber College and Aspiring Human R...,Kanada,61,1,student humber college aspiring human resource...,0.612372,0.500000,0.383511,0.239138,...,0.641753,"[0.08145559, -0.12828213, 0.133419, 0.34408268...",0.675802,0.581192,"[-0.5358244, 0.086343534, 0.16521375, 0.107873...",0.849551,0.833399,"[-0.06980602, 0.34916332, 0.1491546, -0.423699...",0.721071,0.659220
7,8,HR Senior Specialist,San Francisco Bay Area,500,1,hr senior specialist san francisco bay area,0.000000,0.000000,0.000000,0.000000,...,0.593965,"[0.0698105, 0.45483494, 0.05868009, 0.23186374...",0.465558,0.482086,"[-0.4082685, 0.48538813, 0.3310943, 0.05006316...",0.816862,0.807738,"[0.12938498, 0.20963639, 0.2089996, -0.3970928...",0.602913,0.656144
8,10,Seeking Human Resources HRIS and Generalist Po...,Greater Philadelphia Area,500,1,seek human resources hris generalist positions...,0.384900,0.471405,0.146901,0.235587,...,0.693475,"[0.070694834, -0.08755397, 0.059259363, 0.2419...",0.651652,0.712170,"[-0.45893243, 0.24516004, 0.3179749, 0.0450428...",0.849221,0.879234,"[-0.0074006296, 0.46556965, 0.51176244, -0.636...",0.683450,0.774203
9,11,Student at Chapman University,"Lake Forest, California",2,0,student chapman university lake forest california,0.000000,0.000000,0.000000,0.000000,...,0.532900,"[0.43293983, 0.06955156, 0.06899707, 0.1333234...",0.272591,0.217762,"[-0.5080098, 0.30833697, 0.49653065, 0.1399432...",0.751208,0.737659,"[-0.06116784, -0.11885528, -0.08223225, -0.025...",0.529430,0.493900
10,12,"SVP, CHRO, Marketing & Communications, CSR Off...","Houston, Texas Area",500,0,svp chro marketing communications csr officer ...,0.000000,0.000000,0.000000,0.000000,...,0.554451,"[0.025338378, -0.20027564, -0.011067251, 0.093...",0.239620,0.307447,"[-0.781512, 0.090029955, 0.25354826, 0.0460861...",0.789757,0.790620,"[-0.042724065, -0.080167204, 0.0981578, -0.361...",0.482022,0.533534
11,13,Human Resources Coordinator at InterContinenta...,"Atlanta, Georgia",500,1,human resources coordinator intercontinental b...,0.365148,0.447214,0.118302,0.189722,...,0.633586,"[-0.50341177, 0.31778774, -0.33137986, 0.45346...",0.589349,0.585422,"[-0.7381897, 0.48426297, 0.2791259, 0.09066915...",0.823693,0.832860,"[-0.08073535, 0.18883868, 0.20817585, 0.006313...",0.646533,0.680502
12,27,Aspiring Human Resources Management student se...,"Houston, Texas Area",500,1,aspiring human resources management student se...,0.547723,0.447214,0.401339,0.250255,...,0.657543,"[0.05159135, -0.11732758, 0.071188115, 0.53323...",0.710845,0.639502,"[-0.6264965, 0.16711746, 0.21652104, 0.1606061...",0.882906,0.870509,"[-0.054983687, -0.122984886, 0.048353266, -0.4...",0.763715,0.718113
13,28,Seeking Human Resources Opportunities,"Chicago, Illinois",390,1,seek human resources opportunities chicago ill...,0.471405,0.577350,0.172121,0.276034,...,0.822273,"[0.028607085, -0.09097075, 0.22625999, 0.37585...",0.678825,0.712608,"[-0.7631284, 0.059558854, 0.11625934, -0.18359...",0.874558,0.907182,"[-0.46886396, -0.14189017, 0.008217082, -0.331...",0.754647,0.839602
14,66,Experienced Retail Manager and aspiring Human ...,"Austin, Texas Area",57,1,experienced retail manager aspire human resour...,0.365148,0.447214,0.138794,0.222587,...,0.670993,"[-0.1335915, 0.102233164, -0.0676783, 0.596122...",0.615339,0.563026,"[-0.6359693, 0.23222104, 0.47046357, 0.0315299...",0.819730,0.809826,"[-0.46344486, 0.4033751, 0.34756473, 0.2730787...",0.581699,0.621266
15,67,"Human Resources, Staffing and Recruiting Profe...","Jackson, Mississippi Area",500,1,human resources staffing recruiting profession...,0.408248,0.500000,0.144198,0.231253,...,0.704242,"[-0.62990946, 0.01917445, -0.13468212, 0.65892...",0.599808,0.641177,"[-0.5516953, 0.121126965, 0.32738227, 0.142447...",0.864990,0.855313,"[-0.6271638, 0.24108313, 0.1633382, -0.8612581...",0.699184,0.751198
16,68,Human Resources Specialist at Luxottica,Greater New York City Area,500,1,human resources specialist luxottica greater n...,0.384900,0.471405,0.149940,0.240461,...,0.658567,"[0.06840674, -0.16217412, -0.09605427, 0.39077...",0.566897,0.591299,"[-0.4190438, 0.3440408, 0.44111282, 0.04773646...",0.840779,0.837333,"[0.11032573, 0.4116828, 0.4856914, 0.000453142...",0.641775,0.680698
17,69,"Director of Human Resources North America, Gro...","Greater Grand Rapids, Michigan Area",500,1,director human resources north america groupe ...,0.333333,0.408248,0.111073,0.178131,...,0.617171,"[-0.13839705, -0.064350665, -0.01541752, 0.096...",0.566501,0.638929,"[-0.32558498, 0.33788997, 0.39694464, 0.054305...",0.834107,0.834029,"[-0.15402146, 0.30194405, 0.3021368, -0.148372...",0.602055,0.649909
18,70,"Retired Army National Guard Recruiter, office ...","Virginia Beach, Virginia",82,1,retired army national guard recruiter office m...,0.288675,0.353553,0.087842,0.140874,...,0.587433,"[-0.42713434, 0.002501677, -0.14647512, 0.1986...",0.495048,0.547657,"[-0.85571283, 0.39215764, 0.19590104, -0.07532...",0.831278,0.849032,"[-0.55595386, 0.5898834, -0.05791142, -0.66064...",0.639145,0.681945
19,71,"Human Resources Generalist at ScottMadden, Inc.","Raleigh-Durham, North Carolina Area",500,1,human resources generalist scottmadden inc. ra...,0.365148,0.447214,0.132099,0.211850,...,0.597873,"[-0.3715043, 0.11369822, -0.4929816, 0.1071675...",0.585938,0.644923,"[-0.32178524, 0.2995136, 0.3585972, 0.26806474...",0.817869,0.831362,"[0.039709277, 0.5057977, 0.392795, -0.40489027...",0.617503,0.654221
20,72,Business Management Major and Aspiring Human R...,"Monroe, Louisiana Area",5,1,business management major aspiring human resou...,0.547723,0.447214,0.361899,0.225662,...,0.645835,"[-0.03804041, -0.22087835, -0.110205285, 0.199...",0.654317,0.579434,"[-0.44782063, 0.2574412, 0.25465214, -0.000937...",0.862209,0.838993,"[-0.17075573, -0.10971355, 0.29208195, -0.8706...",0.756249,0.705665
21,73,"Aspiring Human Resources Manager, seeking inte...","Houston, Texas Area",7,1,aspiring human resources manager seek internsh...,0.745356,0.730297,0.547299,0.491453,...,0.698324,"[-0.08096075, -0.09674148, 0.09366608, 0.43323...",0.717666,0.656847,"[-0.6963281, 0.25560868, 0.24075904, 0.0969912...",0.897031,0.885686,"[-0.16534856, -0.0564483, -0.09162092, -0.2212...",0.787040,0.766566
22,74,Human Resources Professional,Greater Boston Area,16,1,human resources professional greater boston area,0.471405,0.577350,0.211754,0.339593,...,0.681378,"[-0.09526436, 0.09876554, 0.2901128, 0.2920121...",0.652192,0.660824,"[-0.43740863, 0.5137849, 0.36830768, -0.066041...",0.851635,0.845429,"[-0.1337625, 0.15005594, 0.2668018, -0.7718934...",0.709879,0.738667
23,75,"Nortia Staffing is seeking Human Resources, Pa...","San Jose, California",500,1,nortia staffing seek human resources payroll a...,0.308607,0.377964,0.094809,0.152048,...,0.664826,"[-0.28234896, 0.20026973, -0.029745422, 0.0064...",0.363922,0.431765,"[-0.45602036, -0.13049798, 0.09989647, -0.0306...",0.829859,0.857678,"[-0.110863075, 0.1002836, -0.23174763, -0.4725...",0.610096,0.713768
24,76,Aspiring Human Resources Professional | Passio...,"New York, New York",212,1,aspiring human resources professional | passio...,0.397360,0.324443,0.221303,0.137994,...,0.645239,"[0.10463323, -0.034849808, 0.072006986, 0.3713...",0.689745,0.628447,"[-0.6787435, 0.27065694, 0.20582013, 0.2989907...",0.884487,0.862875,"[-0.30262196, 0.30531693, 0.52543473, -0.27972...",0.784607,0.725922
25,77,Human Resources|\nConflict Management|\nPolici...,Dallas/Fort Worth Area,409,1,human resources| \n conflict management| \n po...,0.288675,0.353553,0.091090,0.146082,...,0.654482,"[0.017995859, 0.13110307, -0.13682944, 0.20777...",0.547561,0.570652,"[-0.6160098, 0.4795794, 0.16522315, -0.1432211...",0.821449,0.823759,"[-0.32043952, 0.2998241, 0.95239764, -0.151168...",0.605259,0.615228
26,78,Human Resources Generalist at Schwan's,Amerika Birlesik Devletleri,500,1,human resources generalist schwan amerika birl...,0.436436,0.534522,0.150329,0.241085,...,0.498734,"[-0.30519372, 0.1990119, -0.3643807, 0.0236742...",0.598948,0.615957,"[-0.57087946, 0.3129471, 0.09804637, 0.1139382...",0.837657,0.849078,"[0.061280113, 0.8112978, 0.5589947, -0.5908352...",0.667303,0.685833
27,79,Liberal Arts Major. Aspiring Human Resources A...,"Baton Rouge, Louisiana Area",7,1,liberal arts major aspire human resources anal...,0.348155,0.426401,0.112435,0.180315,...,0.617225,"[0.073704876, -0.14336641, -0.2691452, 0.43381...",0.572619,0.501982,"[-0.3927466, 0.5657484, 0.18880369, -0.1745542...",0.831977,0.816002,"[-0.42247197, 0.29066586, -0.021244394, -0.025...",0.612939,0.616027
28,80,Junior MES Engineer| Information Systems,"Myrtle Beach, South Carolina Area",52,0,junior mes engineer| information systems myrtl...,0.000000,0.000000,0.000000,0.000000,...,0.565054,"[-0.15650706, 0.22291912, 0.1190338, -0.017217...",0.367070,0.338327,"[-0.5196755, 0.41933462, 0.2315246, -0.4328603...",0.768693,0.761689,"[-0.1488783, 0.060446493, 0.35904175, -0.82315...",0.527361,0.534113
29,81,Senior Human Resources Business Partner at Hei...,"Chattanooga, Tennessee Area",455,1,senior human resources business partner heil e...,0.365148,0.447214,0.119311,0.191341,...,0.657254,"[-0.17593662, 0.4572106, -0.14507309, 0.162415...",0.460896,0.500324,"[-0.7178902, 0.4636007, 0.33357385, -0.0433954...",0.824153,0.824284,"[-0.2569346, 0.22302064, 0.3741188, -0.4970355...",0.592187,0.647515
30,82,Aspiring Human Resources Professional | An ene...,"Austin, Texas Area",174,1,aspiring human resources professional | energe...,0.522233,0.426401,0.319760,0.199387,...,0.669686,"[-0.04500326, 0.3343583, -0.012931807, 0.69893...",0.726663,0.650934,"[-0.83404016, 0.29354206, 0.2467273, 0.0069528...",0.879660,0.850692,"[-0.35192847, 0.8117296, 0.25006095, -0.417006...",0.764258,0.708070
31,83,HR Manager at Endemol Shine North America,"Los Angeles, California",268,1,hr manager endemol shine north america los ang...,0.000000,0.000000,0.000000,0.000000,...,0.556109,"[-0.011515359, -0.06124711, 0.042806327, 0.165...",0.434154,0.469607,"[-0.37314188, 0.28641483, 0.42598328, 0.112691...",0.799531,0.805016,"[-0.23648714, -0.059693594, 0.70311254, -0.189...",0.532248,0.575764
32,84,Human Resources professional for the world lea...,"Highland, California",50,1,human resources professional world leader gis ...,0.384900,0.471405,0.127233,0.204046,...,0.669272,"[-0.072446406, -0.17698306, -0.08454451, 0.097...",0.505218,0.501550,"[-0.7093198, 0.1563751, 0.094563745, -0.103626...",0.815433,0.818604,"[-0.4604214, -0.084645264, 0.38491237, -0.0978...",0.579174,0.615755
33,85,RRP Brand Portfolio Executive at JTI (Japan To...,Greater Philadelphia Area,500,0,rrp brand portfolio executive jti japan tobacc...,0.000000,0.000000,0.000000,0.000000,...,0.556036,"[-0.1277808, 0.18218301, -0.1307597, -0.266775...",0.060906,0.087614,"[-0.46163714, 0.48599944, 0.027181149, -0.0868...",0.760738,0.751162,"[-0.6646173, 0.16491598, -0.11760212, -0.50538...",0.426428,0.446804
34,86,Information Systems Specialist and Programmer ...,"Gaithersburg, Maryland",4,0,information systems specialist programmer love...,0.000000,0.000000,0.000000,0.000000,...,0.556752,"[-0.14152056, 0.08478056, -0.02903051, -0.2863...",0.306089,0.266975,"[-0.5312187, 0.39644995, -0.13633016, -0.33812...",0.779334,0.775224,"[-0.1580629, 0.19408664, 0.20764677, -0.396972...",0.514511,0.525800
35,87,Bachelor of Science in Biology from Victoria U...,"Baltimore, Maryland",40,0,bachelor science biology victoria university w...,0.000000,0.000000,0.000000,0.000000,...,0.506779,"[-0.04654217, 0.06551202, 0.1428736, -0.080360...",0.220378,0.190151,"[-0.6883747, 0.26840305, 0.48082662, 0.3979651...",0.776995,0.768836,"[0.18555036, 0.299443, 0.4513213, -0.21278659,...",0.481234,0.468500
36,88,Human Resources Management Major,"Milpitas, California",18,1,human resources management major milpitas cali...,0.471405,0.577350,0.180339,0.289213,...,0.617728,"[0.10260701, 0.060409836, 0.018907249, 0.44199...",0.606179,0.594265,"[-0.23770311, 0.38630813, 0.24294889, 0.065108...",0.825983,0.837780,"[-0.078399345, 0.029887443, 0.38470793, -0.349...",0.637063,0.679615
37,89,Director Human Resources at EY,Greater Atlanta Area,349,1,director human resources ey greater atlanta ...,0.436436,0.534522,0.175338,0.281193,...,0.682326,"[-0.4573586, 0.086846665, -0.14188299, 0.24838...",0.565116,0.607325,"[-0.60272866, 0.3952733, 0.19139668, 0.2042481...",0.842450,0.851942,"[-0.25956565, 0.18493977, 0.8697246, 0.1434373...",0.641109,0.672451
38,90,Undergraduate Research Assistant at Styczynski...,Greater Atlanta Area,155,0,undergraduate research assistant styczynski la...,0.000000,0.000000,0.000000,0.000000,...,0.517066,"[-0.2180483, 0.17461899, -0.37579802, 0.317437...",0.328335,0.329537,"[-0.60261303, 0.30612013, 0.13125177, 0.165733...",0.799602,0.791786,"[-0.011942126, 0.24363121, 0.4044347, 0.469267...",0.496202,0.505491
39,91,Lead Official at Western Illinois University,Greater Chicago Area,39,0,lead official western illinois university grea...,0.000000,0.000000,0.000000,0.000000,...,0.504603,"[0.0949457, -0.0799265, 0.111112654, -0.563671...",0.239409,0.246103,"[-0.18975331, 0.2834962, 0.25941822, -0.083760...",0.767012,0.750812,"[-0.3121993, -0.06448591, 0.3227936, -0.380759...",0.532021,0.513222
40,92,Seeking employment opportunities within Custom...,"Torrance, California",64,0,seek employment opportunity customer service p...,0.000000,0.000000,0.000000,0.000000,...,0.693326,"[-0.16977556, 0.09300202, 0.16304661, 0.056224...",0.276041,0.358792,"[-0.6161426, 0.107035436, -0.084433354, -0.106...",0.817747,0.832360,"[0.006649693, -0.20672978, -0.051672857, -0.18...",0.540799,0.657590
41,93,Admissions Representative at Community medical...,"Long Beach, California",9,0,admissions representative community medical ce...,0.000000,0.000000,0.000000,0.000000,...,0.521652,"[0.023629846, 0.11685457, 0.17973618, -0.22578...",0.126331,0.164169,"[-0.41647038, 0.47705555, 0.1530416, 0.1298234...",0.768366,0.763693,"[0.16591488, -0.13912347, -0.52723086, -0.1617...",0.439261,0.482994
42,94,Seeking Human Resources Opportunities. Open t...,Amerika Birlesik Devletleri,415,1,seek human resources opportunity open travel...,0.365148,0.447214,0.118204,0.189567,...,0.550735,"[0.24605827, -0.183321, -0.30652106, 0.2478352...",0.410980,0.513562,"[-0.5845617, 0.13208583, 0.16446134, 0.3144301...",0.853530,0.875551,"[0.15406863, -0.15670191, 0.42231083, -0.34260...",0.691485,0.742584
43,95,Student at Westfield State University,"Bridgewater, Massachusetts",57,0,student westfield state university bridgewater...,0.000000,0.000000,0.000000,0.000000,...,0.485235,"[-0.017475367, 0.06770015, 0.47808403, -0.0264...",0.207882,0.185902,"[-0.51726925, 0.3994063, 0.42770147, -0.077130...",0.760195,0.744680,"[0.10071634, -0.30777487, 0.5153912, -0.52441,...",0.504654,0.484886
44,96,Student at Indiana University Kokomo - Busines...,"Lafayette, Indiana",19,0,student indiana university kokomo business man...,0.000000,0.000000,0.000000,0.000000,...,0.542174,"[-0.21228617, 0.17764948, 0.08012094, -0.38919...",0.242628,0.232356,"[-0.53358144, 0.45154014, 0.35825905, -0.20120...",0.772373,0.763788,"[-0.43841854, 0.0744344, 0.6819768, -0.4501927...",0.552099,0.550278
45,98,Student,"Houston, Texas Area",4,0,student houston texas area,0.000000,0.000000,0.000000,0.000000,...,0.573269,"[0.17039593, -0.029945979, 0.46940508, 0.28637...",0.223894,0.222820,"[-0.44304895, 0.48457077, 0.3359063, 0.1310025...",0.765507,0.745525,"[-0.08508128, -0.5465836, 0.20810246, -0.24871...",0.495140,0.486356
46,99,Seeking Human Resources Position,"Las Vegas, Nevada Area",48,1,seek human resources position las vegas nevada...,0.408248,0.500000,0.147019,0.235777,...,0.661059,"[0.2093102, -0.015835505, -0.3244599, 0.690040...",0.708507,0.765440,"[-0.58756346, 0.13135204, 0.16091254, 0.135491...",0.860406,0.894789,"[-0.22036338, -0.04016042, -0.05997374, -0.029...",0.681898,0.789876
47,100,Aspiring Human Resources Manager | Graduating ...,"Cape Girardeau, Missouri",103,1,aspiring human resources manager | graduating ...,0.629941,0.617213,0.321200,0.288425,...,0.624064,"[-0.17863892, 0.060273964, 0.038867954, 0.3832...",0.776213,0.656618,"[-0.5787805, 0.2543999, 0.22224797, 0.01125511...",0.894092,0.873214,"[-0.1259932, 0.50309837, 0.53770906, -0.671567...",0.763419,0.721070
48,101,Human Resources Generalist at Loparex,"Raleigh-Durham, North Carolina Area",500,1,human resources generalist loparex raleigh dur...,0.384900,0.471405,0.145999,0.234142,...,0.613355,"[-0.20525178, -0.018955724, -0.05867168, 0.253...",0.669003,0.712407,"[-0.29734388, 0.28705844, 0.43890628, 0.150678...",0.825495,0.832397,"[-0.041332155, 0.53073823, 0.5158492, -0.36204...",0.612403,0.663845
49,102,Business Intelligence and Analytics at Travelers,Greater New York City Area,49,0,business intelligence analytics travelers grea...,0.000000,0.000000,0.000000,0.000000,...,0.541049,"[0.6286755, -0.39334166, -0.003297218, 0.27370...",0.118182,0.214638,"[-0.21451955, 0.39058736, 0.1634724, -0.050448...",0.762569,0.757943,"[0.38042104, -0.48469934, 0.21905147, -0.47566...",0.425819,0.496481

In [20]:
df.to_csv("../data/vectors_hr_data.csv", index=False)